const sourceLabels = { warehouse: 'WAREHOUSE', supplier: 'SUPPLIER' };
const mechanicLabels = { internal: 'INTERNAL', external: 'EKSTERNAL' };
const crashLevel = (stopsOperation) => stopsOperation ? { label: 'DANGER', tone: 'red' } : { label: 'MINOR', tone: 'green' };

function Badge({ children, tone = 'blue' }) {
  const tones = { blue: 'border-blue-200 bg-blue-50 text-blue-700', green: 'border-emerald-200 bg-emerald-50 text-emerald-700', amber: 'border-amber-200 bg-amber-50 text-amber-700', red: 'border-red-200 bg-red-50 text-red-600' };
  return <span className={`inline-flex whitespace-nowrap border px-2 py-1 text-[10px] font-bold ${tones[tone]}`}>{children}</span>;
}

const formatDate = (value) => value ? new Intl.DateTimeFormat('id-ID', { year: 'numeric', month: '2-digit', day: '2-digit' }).format(new Date(value)) : '-';

export default function DamageLogTable({ logs, page, pageSize, total, onPageChange, onEdit, onResolve, onCancel }) {
  const pageCount = Math.max(1, Math.ceil(total / pageSize));
  return <section className="overflow-hidden border border-[#cbd5e1] bg-[#f8fafc]" aria-label="Damage logs">
    <div className="overflow-x-auto"><table className="w-full min-w-[820px] border-collapse text-left"><thead className="bg-[#e2e8f0] text-[10px] font-bold text-[#334155]"><tr>
      <th className="w-12 px-3 py-3">No</th><th className="px-3 py-3">Item Code</th><th className="px-3 py-3">Jenis Kerusakan</th><th className="px-3 py-3">Tanggal</th><th className="px-3 py-3">Crash Level</th><th className="px-3 py-3">Spare Part</th><th className="px-3 py-3">Mekanik</th><th className="px-3 py-3">Status</th><th className="min-w-[150px] px-3 py-3 text-center">Action</th>
    </tr></thead><tbody className="divide-y divide-[#e2e8f0] text-[11px] text-[#1e293b]">
      {logs.length > 0 ? logs.map((log, index) => { const level = crashLevel(log.stopsOperation); return <tr key={log.id} className="min-h-16 transition hover:bg-[#f1f5f9]"><td className="px-3 py-3 font-medium">{String((page - 1) * pageSize + index + 1).padStart(2, '0')}</td><td className="px-3 py-3 font-bold text-[#08729a]">{log.equipmentItem?.assetCode || '-'}</td><td className="max-w-[250px] px-3 py-3"><p className="font-semibold">{log.description}</p><p className="mt-1 text-[10px] italic text-[#64748b]">{log.damageCode}</p></td><td className="whitespace-nowrap px-3 py-3 text-[#64748b]">{formatDate(log.damageDate)}</td><td className="px-3 py-3"><Badge tone={level.tone}>{level.label}</Badge></td><td className="px-3 py-3"><Badge tone={log.sparePartSource === 'warehouse' ? 'green' : 'amber'}>{sourceLabels[log.sparePartSource] || '-'}</Badge></td><td className="px-3 py-3"><Badge tone={log.mechanicTeam === 'internal' ? 'blue' : 'red'}>{mechanicLabels[log.mechanicTeam] || '-'}</Badge></td><td className="px-3 py-3"><Badge tone={log.status === 'resolved' ? 'blue' : log.status === 'cancelled' ? 'red' : 'amber'}>{log.status.toUpperCase()}</Badge></td><td className="px-3 py-3"><div className="flex flex-wrap justify-center gap-1"><button type="button" onClick={() => onEdit(log)} className="grid h-8 w-8 place-items-center border border-[#cbd5e1] text-base text-[#08729a] transition hover:bg-white" aria-label={`Edit ${log.damageCode}`} title="Edit">↗</button>{log.status === 'reported' && <button type="button" onClick={() => onResolve(log)} className="grid h-8 w-8 place-items-center border border-emerald-300 bg-emerald-50 text-base font-bold text-emerald-700 hover:bg-emerald-100" aria-label={`Resolve ${log.damageCode}`} title="Resolve">✓</button>}{(log.status === 'reported' || log.status === 'resolved') && <button type="button" onClick={() => onCancel(log)} className="grid h-8 w-8 place-items-center border border-red-300 bg-red-50 text-base font-bold text-red-700 hover:bg-red-100" aria-label={`Cancel ${log.damageCode}`} title="Cancel">×</button>}</div></td></tr>; }) : <tr><td colSpan="9" className="px-3 py-12 text-center text-xs text-[#64748b]">Belum ada laporan kerusakan yang sesuai.</td></tr>}
    </tbody></table></div><footer className="flex flex-wrap items-center justify-between gap-2 border-t border-[#cbd5e1] bg-[#e8eef5] px-3 py-3 text-[10px] text-[#475569]"><span>Menampilkan {total === 0 ? 0 : (page - 1) * pageSize + 1}-{Math.min(page * pageSize, total)} dari {total} laporan</span><div className="flex items-center gap-1" aria-label="Pagination"><button type="button" disabled={page === 1} onClick={() => onPageChange(page - 1)} className="grid h-7 w-7 place-items-center border border-[#cbd5e1] bg-white text-sm disabled:opacity-40" aria-label="Previous page">‹</button>{Array.from({ length: pageCount }, (_, index) => index + 1).slice(0, 5).map((number) => <button type="button" key={number} onClick={() => onPageChange(number)} className={`grid h-7 w-7 place-items-center border text-[10px] ${page === number ? 'border-[#08729a] bg-[#08729a] text-white' : 'border-[#cbd5e1] bg-white text-[#334155]'}`}>{number}</button>)}<button type="button" disabled={page === pageCount} onClick={() => onPageChange(page + 1)} className="grid h-7 w-7 place-items-center border border-[#cbd5e1] bg-white text-sm disabled:opacity-40" aria-label="Next page">›</button></div></footer>
  </section>;
}
